//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesSaferbo.SOAP.ServientregaRecogida {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePickUpRequest", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ResponsePickUpRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.KindOfIssue ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.PickUpRequest[] PickUpRequestListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.KindOfIssue Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.PickUpRequest[] PickUpRequestList {
            get {
                return this.PickUpRequestListField;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpRequestListField, value) != true)) {
                    this.PickUpRequestListField = value;
                    this.RaisePropertyChanged("PickUpRequestList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KindOfIssue", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Enums")]
    [System.SerializableAttribute()]
    public partial class KindOfIssue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdError {
            get {
                return this.IdErrorField;
            }
            set {
                if ((this.IdErrorField.Equals(value) != true)) {
                    this.IdErrorField = value;
                    this.RaisePropertyChanged("IdError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PickUpRequest", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication")]
    [System.SerializableAttribute()]
    public partial class PickUpRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.Document[] DocumentListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PickupRequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPiecesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryTime {
            get {
                return this.DeliveryTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTimeField, value) != true)) {
                    this.DeliveryTimeField = value;
                    this.RaisePropertyChanged("DeliveryTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.Document[] DocumentList {
            get {
                return this.DocumentListField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentListField, value) != true)) {
                    this.DocumentListField = value;
                    this.RaisePropertyChanged("DocumentList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PickupRequestNumber {
            get {
                return this.PickupRequestNumberField;
            }
            set {
                if ((this.PickupRequestNumberField.Equals(value) != true)) {
                    this.PickupRequestNumberField = value;
                    this.RaisePropertyChanged("PickupRequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnAdress {
            get {
                return this.ReturnAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnAdressField, value) != true)) {
                    this.ReturnAdressField = value;
                    this.RaisePropertyChanged("ReturnAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCity {
            get {
                return this.ReturnCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCityField, value) != true)) {
                    this.ReturnCityField = value;
                    this.RaisePropertyChanged("ReturnCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDocuments {
            get {
                return this.TotalDocumentsField;
            }
            set {
                if ((this.TotalDocumentsField.Equals(value) != true)) {
                    this.TotalDocumentsField = value;
                    this.RaisePropertyChanged("TotalDocuments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPieces {
            get {
                return this.TotalPiecesField;
            }
            set {
                if ((this.TotalPiecesField.Equals(value) != true)) {
                    this.TotalPiecesField = value;
                    this.RaisePropertyChanged("TotalPieces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDetailPickUp", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseDetailPickUp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CancelCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CancelDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberPickUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CancelComment {
            get {
                return this.CancelCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelCommentField, value) != true)) {
                    this.CancelCommentField = value;
                    this.RaisePropertyChanged("CancelComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CancelDate {
            get {
                return this.CancelDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelDateField, value) != true)) {
                    this.CancelDateField = value;
                    this.RaisePropertyChanged("CancelDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberPickUp {
            get {
                return this.NumberPickUpField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberPickUpField, value) != true)) {
                    this.NumberPickUpField = value;
                    this.RaisePropertyChanged("NumberPickUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idError {
            get {
                return this.idErrorField;
            }
            set {
                if ((this.idErrorField.Equals(value) != true)) {
                    this.idErrorField = value;
                    this.RaisePropertyChanged("idError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCancel", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseCancel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberPickUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberPickUp {
            get {
                return this.NumberPickUpField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberPickUpField, value) != true)) {
                    this.NumberPickUpField = value;
                    this.RaisePropertyChanged("NumberPickUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stateResponse {
            get {
                return this.stateResponseField;
            }
            set {
                if ((this.stateResponseField.Equals(value) != true)) {
                    this.stateResponseField = value;
                    this.RaisePropertyChanged("stateResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseValidTimePickup", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseValidTimePickup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndHourPickUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndHourRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartHourPickUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartHourRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndHourPickUp {
            get {
                return this.EndHourPickUpField;
            }
            set {
                if ((object.ReferenceEquals(this.EndHourPickUpField, value) != true)) {
                    this.EndHourPickUpField = value;
                    this.RaisePropertyChanged("EndHourPickUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndHourRequest {
            get {
                return this.EndHourRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.EndHourRequestField, value) != true)) {
                    this.EndHourRequestField = value;
                    this.RaisePropertyChanged("EndHourRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartHourPickUp {
            get {
                return this.StartHourPickUpField;
            }
            set {
                if ((object.ReferenceEquals(this.StartHourPickUpField, value) != true)) {
                    this.StartHourPickUpField = value;
                    this.RaisePropertyChanged("StartHourPickUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartHourRequest {
            get {
                return this.StartHourRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.StartHourRequestField, value) != true)) {
                    this.StartHourRequestField = value;
                    this.RaisePropertyChanged("StartHourRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDocumentPickUp", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceDocumentPickUp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodDaneCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionRecoleccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoRecolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaSolicitudRecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_EstadoRecolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoNoRecoleccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServicesSaferbo.SOAP.ServientregaRecogida.ServiceDocumentPickUp_Mov[] ServiceDocumentPickUpMovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltObservacionMobileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodDaneCiudad {
            get {
                return this.CodDaneCiudadField;
            }
            set {
                if ((this.CodDaneCiudadField.Equals(value) != true)) {
                    this.CodDaneCiudadField = value;
                    this.RaisePropertyChanged("CodDaneCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionRecoleccion {
            get {
                return this.DireccionRecoleccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionRecoleccionField, value) != true)) {
                    this.DireccionRecoleccionField = value;
                    this.RaisePropertyChanged("DireccionRecoleccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoRecol {
            get {
                return this.EstadoRecolField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoRecolField, value) != true)) {
                    this.EstadoRecolField = value;
                    this.RaisePropertyChanged("EstadoRecol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCreacionField, value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaSolicitudRec {
            get {
                return this.FechaSolicitudRecField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaSolicitudRecField, value) != true)) {
                    this.FechaSolicitudRecField = value;
                    this.RaisePropertyChanged("FechaSolicitudRec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_EstadoRecol {
            get {
                return this.Id_EstadoRecolField;
            }
            set {
                if ((this.Id_EstadoRecolField.Equals(value) != true)) {
                    this.Id_EstadoRecolField = value;
                    this.RaisePropertyChanged("Id_EstadoRecol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoNoRecoleccion {
            get {
                return this.MotivoNoRecoleccionField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoNoRecoleccionField, value) != true)) {
                    this.MotivoNoRecoleccionField = value;
                    this.RaisePropertyChanged("MotivoNoRecoleccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Movimiento {
            get {
                return this.MovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.MovimientoField, value) != true)) {
                    this.MovimientoField = value;
                    this.RaisePropertyChanged("Movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCiudad {
            get {
                return this.NombreCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCiudadField, value) != true)) {
                    this.NombreCiudadField = value;
                    this.RaisePropertyChanged("NombreCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDepartamento {
            get {
                return this.NombreDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDepartamentoField, value) != true)) {
                    this.NombreDepartamentoField = value;
                    this.RaisePropertyChanged("NombreDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSolicitud {
            get {
                return this.NumeroSolicitudField;
            }
            set {
                if ((this.NumeroSolicitudField.Equals(value) != true)) {
                    this.NumeroSolicitudField = value;
                    this.RaisePropertyChanged("NumeroSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ServiceDocumentPickUp_Mov[] ServiceDocumentPickUpMov {
            get {
                return this.ServiceDocumentPickUpMovField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceDocumentPickUpMovField, value) != true)) {
                    this.ServiceDocumentPickUpMovField = value;
                    this.RaisePropertyChanged("ServiceDocumentPickUpMov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltObservacionMobile {
            get {
                return this.UltObservacionMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.UltObservacionMobileField, value) != true)) {
                    this.UltObservacionMobileField = value;
                    this.RaisePropertyChanged("UltObservacionMobile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDocumentPickUp_Mov", Namespace="http://schemas.datacontract.org/2004/07/DomainApplication.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceDocumentPickUp_Mov : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string movimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noRecoleccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionSolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaMovimiento {
            get {
                return this.fechaMovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaMovimientoField, value) != true)) {
                    this.fechaMovimientoField = value;
                    this.RaisePropertyChanged("fechaMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string movimiento {
            get {
                return this.movimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.movimientoField, value) != true)) {
                    this.movimientoField = value;
                    this.RaisePropertyChanged("movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noRecoleccion {
            get {
                return this.noRecoleccionField;
            }
            set {
                if ((object.ReferenceEquals(this.noRecoleccionField, value) != true)) {
                    this.noRecoleccionField = value;
                    this.RaisePropertyChanged("noRecoleccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacionSolicitud {
            get {
                return this.observacionSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionSolicitudField, value) != true)) {
                    this.observacionSolicitudField = value;
                    this.RaisePropertyChanged("observacionSolicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServientregaRecogida.IPickUpRequest")]
    public interface IPickUpRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/CreateRequestSporadic", ReplyAction="http://tempuri.org/IPickUpRequest/CreateRequestSporadicResponse")]
        WebServicesSaferbo.SOAP.ServientregaRecogida.ResponsePickUpRequest CreateRequestSporadic(string[] lstGuides, string pickUpDate, string pickUpHour, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/CreateRequestSporadic", ReplyAction="http://tempuri.org/IPickUpRequest/CreateRequestSporadicResponse")]
        System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponsePickUpRequest> CreateRequestSporadicAsync(string[] lstGuides, string pickUpDate, string pickUpHour, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/GetDetailPickUp", ReplyAction="http://tempuri.org/IPickUpRequest/GetDetailPickUpResponse")]
        WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseDetailPickUp GetDetailPickUp(int DocumentPickUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/GetDetailPickUp", ReplyAction="http://tempuri.org/IPickUpRequest/GetDetailPickUpResponse")]
        System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseDetailPickUp> GetDetailPickUpAsync(int DocumentPickUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/CancelPickUp", ReplyAction="http://tempuri.org/IPickUpRequest/CancelPickUpResponse")]
        WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseCancel CancelPickUp(int DocumentPickUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/CancelPickUp", ReplyAction="http://tempuri.org/IPickUpRequest/CancelPickUpResponse")]
        System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseCancel> CancelPickUpAsync(int DocumentPickUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/getValidTimePickup", ReplyAction="http://tempuri.org/IPickUpRequest/getValidTimePickupResponse")]
        WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseValidTimePickup getValidTimePickup(int idCountry, int idCity, int idProduct, int idSubProduct, int DayPickUp, int idTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/getValidTimePickup", ReplyAction="http://tempuri.org/IPickUpRequest/getValidTimePickupResponse")]
        System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseValidTimePickup> getValidTimePickupAsync(int idCountry, int idCity, int idProduct, int idSubProduct, int DayPickUp, int idTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/getDetailMovementPickUp", ReplyAction="http://tempuri.org/IPickUpRequest/getDetailMovementPickUpResponse")]
        WebServicesSaferbo.SOAP.ServientregaRecogida.ServiceDocumentPickUp[] getDetailMovementPickUp(int DocumentPickUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPickUpRequest/getDetailMovementPickUp", ReplyAction="http://tempuri.org/IPickUpRequest/getDetailMovementPickUpResponse")]
        System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ServiceDocumentPickUp[]> getDetailMovementPickUpAsync(int DocumentPickUp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPickUpRequestChannel : WebServicesSaferbo.SOAP.ServientregaRecogida.IPickUpRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PickUpRequestClient : System.ServiceModel.ClientBase<WebServicesSaferbo.SOAP.ServientregaRecogida.IPickUpRequest>, WebServicesSaferbo.SOAP.ServientregaRecogida.IPickUpRequest {
        
        public PickUpRequestClient() {
        }
        
        public PickUpRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PickUpRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PickUpRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PickUpRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponsePickUpRequest CreateRequestSporadic(string[] lstGuides, string pickUpDate, string pickUpHour, string comments) {
            return base.Channel.CreateRequestSporadic(lstGuides, pickUpDate, pickUpHour, comments);
        }
        
        public System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponsePickUpRequest> CreateRequestSporadicAsync(string[] lstGuides, string pickUpDate, string pickUpHour, string comments) {
            return base.Channel.CreateRequestSporadicAsync(lstGuides, pickUpDate, pickUpHour, comments);
        }
        
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseDetailPickUp GetDetailPickUp(int DocumentPickUp) {
            return base.Channel.GetDetailPickUp(DocumentPickUp);
        }
        
        public System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseDetailPickUp> GetDetailPickUpAsync(int DocumentPickUp) {
            return base.Channel.GetDetailPickUpAsync(DocumentPickUp);
        }
        
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseCancel CancelPickUp(int DocumentPickUp) {
            return base.Channel.CancelPickUp(DocumentPickUp);
        }
        
        public System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseCancel> CancelPickUpAsync(int DocumentPickUp) {
            return base.Channel.CancelPickUpAsync(DocumentPickUp);
        }
        
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseValidTimePickup getValidTimePickup(int idCountry, int idCity, int idProduct, int idSubProduct, int DayPickUp, int idTime) {
            return base.Channel.getValidTimePickup(idCountry, idCity, idProduct, idSubProduct, DayPickUp, idTime);
        }
        
        public System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ResponseValidTimePickup> getValidTimePickupAsync(int idCountry, int idCity, int idProduct, int idSubProduct, int DayPickUp, int idTime) {
            return base.Channel.getValidTimePickupAsync(idCountry, idCity, idProduct, idSubProduct, DayPickUp, idTime);
        }
        
        public WebServicesSaferbo.SOAP.ServientregaRecogida.ServiceDocumentPickUp[] getDetailMovementPickUp(int DocumentPickUp) {
            return base.Channel.getDetailMovementPickUp(DocumentPickUp);
        }
        
        public System.Threading.Tasks.Task<WebServicesSaferbo.SOAP.ServientregaRecogida.ServiceDocumentPickUp[]> getDetailMovementPickUpAsync(int DocumentPickUp) {
            return base.Channel.getDetailMovementPickUpAsync(DocumentPickUp);
        }
    }
}
